# Generated by Django 5.2.14 on 2026-05-16 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movies', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='guests.guest')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='Movies.movie')),
            ],
        ),
    ]
